version: 2
defaults: &defaults
  docker:
    - image: circleci/node:10
  working_directory: ~/project
jobs:
  install-dependencies:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package.json" }}
            - dependencies-
      - run: |
          yarn install --frozen-lockfile
      - save_cache:
          key: dependencies-{{ checksum "package.json" }}
          paths: node_modules
      - persist_to_workspace:
          root: .
          paths: .

  lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run: |
          yarn lint

  unit-tests:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run: |
          yarn test --coverage
          cat ./coverage/lcov.info | ./node_modules/.bin/codecov
          bash .circleci/comment-artifacts.sh
      - store_artifacts:
          path: coverage
          destination: coverage

  build-example:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run: |
          yarn parcel build example/index.html
      - store_artifacts:
          path: dist
          destination: dist

workflows:
  version: 2
  build-and-test:
    jobs:
      - install-dependencies
      - lint:
          requires:
            - install-dependencies
      - unit-tests:
          requires:
            - install-dependencies
      - build-example:
          requires:
            - install-dependencies
